name: caterfy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.6
  supabase_flutter: ^2.10.1
  sign_in_with_apple: ^6.0.0
  flutter_spinkit: ^5.2.2
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.12.0
  google_sign_in: ^6.1.5
  http: ^1.6.0
  pinput: ^5.0.2
  toastification: ^3.0.3
  flutter_skeleton_ui: ^0.0.6
  google_maps_flutter: ^2.14.0
  geocoding: ^2.1.5
  geolocator: ^14.0.2
  flutter_local_notifications: ^19.5.0
  skeletonizer: ^2.1.1
  scrollable_positioned_list: ^0.3.8
  animated_digit: ^3.3.2
  animated_flip_counter: ^0.3.4
  image_picker: ^1.2.1
  dotted_border: ^3.1.0
  uuid: ^4.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^11.0.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans_36pt-Regular.ttf
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/map_style_dark.json

flutter_native_splash:
  color: "#6e44d2"
  image: assets/images/caterfy_splash.png
  android: true
  ios: true

  android_12:
    color: "#6e44d2"
    image: assets/images/caterfy_splash.png
